#ifndef _ITEM_TYPE_H
#define _ITEM_TYPE_H

#include "enum_variant.h"

enum class ItemId { KNIFE,
  SPEAR,
  SWORD,
  FLAMING_SWORD,
  SPECIAL_SWORD,
  ELVEN_SWORD,
  SPECIAL_ELVEN_SWORD,
  BATTLE_AXE,
  SPECIAL_BATTLE_AXE,
  WAR_HAMMER,
  SPECIAL_WAR_HAMMER,
  SCYTHE,
  BOW,
  ARROW,

  LEATHER_ARMOR,
  LEATHER_HELM,
  TELEPATHY_HELM,
  CHAIN_ARMOR,
  IRON_HELM,
  LEATHER_BOOTS,
  IRON_BOOTS,
  SPEED_BOOTS,
  LEVITATION_BOOTS,
  LEATHER_GLOVES,
  DEXTERITY_GLOVES,
  STRENGTH_GLOVES,
  ROBE,

  SCROLL,
  FIRE_SCROLL,
  POTION,
  MUSHROOM,

  WARNING_AMULET,
  HEALING_AMULET,
  DEFENSE_AMULET,
  FRIENDLY_ANIMALS_AMULET,

  FIRE_RESIST_RING,
  POISON_RESIST_RING,

  FIRST_AID_KIT,
  ROCK,
  IRON_ORE,
  GOLD_PIECE,
  WOOD_PLANK,

  TECH_BOOK,
  IRON_WORKING_BOOK,
  ALCHEMY_ADV_BOOK,
  SPELLS_MAS_BOOK,
  HUMANOID_MUT_BOOK,
  BEAST_MUT_BOOK,

  BOULDER_TRAP_ITEM,
  GAS_TRAP_ITEM,
  ALARM_TRAP_ITEM,
  WEB_TRAP_ITEM,
  SURPRISE_TRAP_ITEM,
  TERROR_TRAP_ITEM,
};

typedef EnumVariant<ItemId,
        ASSIGN(EffectType, ItemId::SCROLL, ItemId::POTION, ItemId::MUSHROOM)> ItemType;

#endif
