#ifndef _MODIFIER_H
#define _MODIFIER_H

RICH_ENUM(ModifierType,
  DAMAGE,
  ACCURACY,
  THROWN_DAMAGE,
  THROWN_ACCURACY,
  FIRED_DAMAGE,
  FIRED_ACCURACY,
  DEFENSE,
  INV_LIMIT
);

RICH_ENUM(AttrType,
  STRENGTH,
  DEXTERITY,
  SPEED
);

enum class AttackType { CUT, STAB, CRUSH, PUNCH, BITE, EAT, HIT, SHOOT, SPELL, POSSESS};

#endif
