#ifndef _STDAFX_H
#define _STDAFX_H

#include <iostream>
#include <fstream>
#include <algorithm>
#include <sstream>
#include <string>
#include <cstdlib>
#include <vector>
#include <string>
#include <memory>
#include "ctype.h"
#include <cstring>
#include <set>
#include <time.h>
#include <cstdlib>
#include <sys/time.h>
#include <typeinfo>
#include <unordered_set>
#include <unordered_map>
#include <map>
#include <queue>
#include <random>
#include <stdexcept>
#include <tuple>
#include <thread>
#include <stack>
#include <typeinfo>

using std::string;
using std::vector;
using std::map;
using std::queue;
using std::unique_ptr;
using std::default_random_engine;
using std::function;
using std::initializer_list;
using std::unordered_set;
using std::pair;
using std::tuple;
using std::set;
using std::out_of_range;
using std::unordered_map;
using std::min;
using std::max;
using std::ofstream;
using std::ifstream;
using std::endl;
using std::priority_queue;
using std::make_pair;
using std::stack;

/*#include "window_view.h"
#include "action.h"
#include "attack.h"
#include "collective.h"
#include "collective_action.h"
#include "controller.h"
#include "creature_attributes.h"
#include "creature_factory.h"
#include "creature_view.h"
#include "creature.h"
#include "debug.h"
#include "effect.h"
#include "enemy_check.h"
#include "enums.h"
#include "equipment.h"
#include "event.h"
#include "field_of_view.h"
#include "fire.h"
#include "inventory.h"
#include "item_attributes.h"
#include "item_factory.h"
#include "item.h"
#include "level_generator.h"
#include "level.h"
#include "level_maker.h"
#include "location.h"
#include "logging_view.h"
#include "map_layout.h"
#include "map_memory.h"
#include "markov_chain.h"
#include "message_buffer.h"
#include "minion_equipment.h"
#include "model.h"
#include "monster.h"
#include "monster_ai.h"
#include "name_generator.h"
#include "pantheon.h"
#include "player.h"
#include "poison_gas.h"
#include "quest.h"
#include "ranged_weapon.h"
#include "replay_view.h"
#include "shortest_path.h"
#include "skill.h"
#include "square_factory.h"
#include "square.h"
#include "task.h"
#include "time_queue.h"
#include "timer_var.h"
#include "tribe.h"
#include "trigger.h"
#include "util.h"
#include "view.h"
#include "view_index.h"
#include "view_object.h"
#include "village_control.h"*/

#endif
