#pragma once

#include "util.h"

RICH_ENUM(TutorialHighlight,
  DIG_OR_CUT_TREES,
  RESOURCE_STORAGE,
  EQUIPMENT_STORAGE,
  WOOD_RESOURCE,
  ACCEPT_IMMIGRANT,
  BUILD_DOOR,
  TRAINING_ROOM,
  BUILD_BED,
  BUILD_LIBRARY,
  BUILD_TORCH,
  BUILD_FLOOR,
  BUILD_WORKSHOP,
  REMOVE_CONSTRUCTION,
  SCHEDULE_CLUB,
  EQUIPMENT_SLOT_WEAPON,
  NEW_TEAM,
  CONTROL_TEAM,
  LEAVE_CONTROL,
  FULL_CONTROL,
  MINIMAP_BUTTONS,
  RESEARCH,
  HELP_TAB
);

